package utfpr.gui;

import java.util.HashMap;
import java.util.Map;
import javax.swing.JLabel;
import javax.swing.JRootPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableModel;
import utfpr.banco.Cliente;

public class ListaClientes extends javax.swing.JInternalFrame {

    HashMap<Integer, Cliente> clientes;

    /**
     * Creates new form ListaClientes
     */
    public ListaClientes(HashMap dados) {
        initComponents();
        remove_title_bar();
        this.clientes = dados;
        carregarDados();
    }

    private void carregarDados() {
        /*Transforma a listagem de clientes em um objeto que 
          possa ser reconhecido e apresentado na tabela*/

        TableModel tm = toTableModel(clientes);
        tblClientes.setModel(tm);
        configurarTabela();
    }

    private TableModel toTableModel(HashMap<Integer, Cliente> map) {

        DefaultTableModel model = new DefaultTableModel(
                new String[]{"Código", "Nome", "Endereço"}, 0)//cabeçalhos da tabela
        {
            Class[] types = new Class[]{String.class, String.class, String.class}; //define o formato de apresentação das colunas
            boolean[] canEdit = new boolean[]{false, false, false}; //define que não pode editar os valores

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };

        for (Map.Entry<Integer, Cliente> entry : map.entrySet()) {
            model.addRow(new Object[]{entry.getValue().getCod(), entry.getValue().getNome(), entry.getValue().getEndereco()});
        }
        return model;
    }

    private void configurarTabela() {
        //Ajusta o alinhamento do texto do cabeçalho para a esquerda
        DefaultTableCellRenderer renderer = (DefaultTableCellRenderer) tblClientes.getTableHeader().getDefaultRenderer();
        renderer.setHorizontalAlignment(JLabel.LEFT);
        
        //Ajusta o tamanho das colunas para ficar mais bonito
        if (tblClientes.getColumnModel().getColumnCount() > 0) {
            tblClientes.getColumnModel().getColumn(0).setMinWidth(50);
            tblClientes.getColumnModel().getColumn(0).setMaxWidth(100);
            tblClientes.getColumnModel().getColumn(1).setMinWidth(200);
            tblClientes.getColumnModel().getColumn(2).setMinWidth(100);
        }

    }

    private void remove_title_bar() {
        putClientProperty("ListaClientes.isPalette", Boolean.TRUE);
        getRootPane().setWindowDecorationStyle(JRootPane.NONE);
        ((BasicInternalFrameUI) this.getUI()).setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        lblBancoNome = new javax.swing.JLabel();

        setBackground(java.awt.SystemColor.window);
        setBorder(null);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tblClientes.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Código", "Nome", "Endereço"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblClientes.setAutoscrolls(false);
        tblClientes.setGridColor(java.awt.SystemColor.controlLtHighlight);
        tblClientes.setOpaque(false);
        tblClientes.setRowHeight(20);
        tblClientes.getTableHeader().setReorderingAllowed(false);
        tblClientes.setUpdateSelectionOnSort(false);
        jScrollPane1.setViewportView(tblClientes);
        if (tblClientes.getColumnModel().getColumnCount() > 0) {
            tblClientes.getColumnModel().getColumn(0).setMinWidth(50);
            tblClientes.getColumnModel().getColumn(0).setMaxWidth(100);
            tblClientes.getColumnModel().getColumn(1).setMinWidth(200);
            tblClientes.getColumnModel().getColumn(2).setMinWidth(100);
        }

        lblBancoNome.setBackground(java.awt.SystemColor.inactiveCaption);
        lblBancoNome.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lblBancoNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBancoNome.setText("Clientes");
        lblBancoNome.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBancoNome, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblBancoNome)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBancoNome;
    private javax.swing.JTable tblClientes;
    // End of variables declaration//GEN-END:variables
}
