package utfpr.gui;

import java.text.DecimalFormat;
import javax.swing.JRootPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import utfpr.banco.Banco;
import utfpr.banco.ContaBancaria;
import utfpr.banco.ContaCorrente;

public class ListaSaldos extends javax.swing.JInternalFrame {

    private Banco banco;
    private static final DecimalFormat df = new DecimalFormat("0.00");

    /**
     * Creates new form ListaSaldos
     * @param banco Banco que se deseja apresentar
     */
    public ListaSaldos(Banco banco) {
        initComponents();
        remove_title_bar();
        this.banco = banco;
        carregarSaldos();
    }

    private void remove_title_bar() {
        putClientProperty("ListaClientes.isPalette", Boolean.TRUE);
        getRootPane().setWindowDecorationStyle(JRootPane.NONE);
        ((BasicInternalFrameUI) this.getUI()).setNorthPane(null);

    }

    public void setBanco(Banco banco) {
        this.banco = banco;
    }

    private void carregarSaldos() {
        ContaBancaria aux;

        lblBancoNome.setText(banco.getNome());
        txtSaldoMedio.setText("R$ " + df.format(banco.getSaldoMedioContas()));
        txtSaldoMedioCC.setText("R$ " + df.format(banco.getSaldoMedioContasCorrente()));
        txtSaldoMedioCP.setText("R$ " + df.format(banco.getSaldoMedioContasPupanca()));

        aux = banco.getContaMenorSaldo();
        txtMenorSaldoValor.setText("R$ " + df.format(aux.getSaldo()));
        lblMenorSaldoTitular.setText(aux.getNumero() + " - " + aux.getTitular().getNome());
        if (aux instanceof ContaCorrente) {
            lblMenorSaldoTipo.setText("Conta corrente");
        } else {
            lblMenorSaldoTipo.setText("Conta poupança");
        }

        aux = banco.getContaMaiorSaldo();
        txtMaiorSaldoValor.setText("R$ " + df.format(aux.getSaldo()));
        lblMaiorSaldoTitular.setText(aux.getNumero() + " - " + aux.getTitular().getNome());
        if (aux instanceof ContaCorrente) {
            lblMaiorSaldoTipo.setText("Conta corrente");
        } else {
            lblMaiorSaldoTipo.setText("Conta poupança");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMenorSaldoTipo = new javax.swing.JLabel();
        lblSaldoMedioCC = new javax.swing.JLabel();
        lblMaiorSaldoTitular = new javax.swing.JLabel();
        txtSaldoMedioCC = new javax.swing.JFormattedTextField();
        lblMaiorSaldo = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblMaiorSaldoTipo = new javax.swing.JLabel();
        lblSaldoMedioCP = new javax.swing.JLabel();
        txtMaiorSaldoValor = new javax.swing.JFormattedTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        lblBancoNome = new javax.swing.JLabel();
        txtSaldoMedioCP = new javax.swing.JFormattedTextField();
        lblSaldoMedio = new javax.swing.JLabel();
        lblMenorSaldo = new javax.swing.JLabel();
        txtMenorSaldoValor = new javax.swing.JFormattedTextField();
        jPanel7 = new javax.swing.JPanel();
        txtSaldoMedio = new javax.swing.JFormattedTextField();
        lblMenorSaldoTitular = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setBackground(java.awt.SystemColor.window);
        setBorder(null);

        lblMenorSaldoTipo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblMenorSaldoTipo.setText("Tipo");

        lblSaldoMedioCC.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblSaldoMedioCC.setText("Saldo médio contas correntes");

        lblMaiorSaldoTitular.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblMaiorSaldoTitular.setText("Codigo - Titular");

        txtSaldoMedioCC.setEditable(false);
        txtSaldoMedioCC.setBackground(java.awt.SystemColor.text);
        txtSaldoMedioCC.setBorder(null);
        txtSaldoMedioCC.setForeground(new java.awt.Color(57, 102, 159));
        txtSaldoMedioCC.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("R$ #,##0.###"))));
        txtSaldoMedioCC.setText("R$ 0,00");
        txtSaldoMedioCC.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txtSaldoMedioCC.setOpaque(false);

        lblMaiorSaldo.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lblMaiorSaldo.setText("Conta com maior saldo");

        jPanel5.setBackground(new java.awt.Color(57, 102, 159));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
        );

        lblMaiorSaldoTipo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblMaiorSaldoTipo.setText("Tipo");

        lblSaldoMedioCP.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblSaldoMedioCP.setText("Saldo médio contas poupanças");

        txtMaiorSaldoValor.setEditable(false);
        txtMaiorSaldoValor.setBackground(java.awt.SystemColor.text);
        txtMaiorSaldoValor.setBorder(null);
        txtMaiorSaldoValor.setForeground(new java.awt.Color(0, 150, 115));
        txtMaiorSaldoValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("R$ #,##0.###"))));
        txtMaiorSaldoValor.setText("R$ 0,00");
        txtMaiorSaldoValor.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txtMaiorSaldoValor.setOpaque(false);

        jPanel4.setBackground(new java.awt.Color(57, 102, 159));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(0, 150, 115));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 131, Short.MAX_VALUE)
        );

        lblBancoNome.setBackground(java.awt.SystemColor.inactiveCaption);
        lblBancoNome.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lblBancoNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBancoNome.setText("NOME DO BANCO");
        lblBancoNome.setOpaque(true);

        txtSaldoMedioCP.setEditable(false);
        txtSaldoMedioCP.setBackground(java.awt.SystemColor.text);
        txtSaldoMedioCP.setBorder(null);
        txtSaldoMedioCP.setForeground(new java.awt.Color(57, 102, 159));
        txtSaldoMedioCP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("R$ #,##0.###"))));
        txtSaldoMedioCP.setText("R$ 0,00");
        txtSaldoMedioCP.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txtSaldoMedioCP.setOpaque(false);

        lblSaldoMedio.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblSaldoMedio.setText("Saldo médio");

        lblMenorSaldo.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lblMenorSaldo.setText("Conta com menor saldo");

        txtMenorSaldoValor.setEditable(false);
        txtMenorSaldoValor.setBackground(java.awt.SystemColor.text);
        txtMenorSaldoValor.setBorder(null);
        txtMenorSaldoValor.setForeground(new java.awt.Color(239, 162, 82));
        txtMenorSaldoValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("R$ #,##0.###"))));
        txtMenorSaldoValor.setText("R$ 0,00");
        txtMenorSaldoValor.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txtMenorSaldoValor.setOpaque(false);

        jPanel7.setBackground(new java.awt.Color(239, 162, 82));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 131, Short.MAX_VALUE)
        );

        txtSaldoMedio.setEditable(false);
        txtSaldoMedio.setBackground(java.awt.SystemColor.text);
        txtSaldoMedio.setBorder(null);
        txtSaldoMedio.setForeground(new java.awt.Color(57, 102, 159));
        txtSaldoMedio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("R$ #,##0.###"))));
        txtSaldoMedio.setText("R$ 0,00");
        txtSaldoMedio.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txtSaldoMedio.setOpaque(false);

        lblMenorSaldoTitular.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblMenorSaldoTitular.setText("Codigo - Titular");

        jPanel2.setBackground(new java.awt.Color(57, 102, 159));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lblSaldoMedio))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSaldoMedio, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lblSaldoMedioCC))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSaldoMedioCC, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lblSaldoMedioCP))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSaldoMedioCP, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMenorSaldo)
                    .addComponent(lblMenorSaldoTitular)
                    .addComponent(txtMenorSaldoValor, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMenorSaldoTipo))
                .addGap(83, 83, 83)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMaiorSaldo)
                    .addComponent(lblMaiorSaldoTitular)
                    .addComponent(txtMaiorSaldoValor, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaiorSaldoTipo))
                .addGap(137, 137, 137))
            .addComponent(lblBancoNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblBancoNome)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSaldoMedioCP)
                        .addGap(20, 20, 20)
                        .addComponent(txtSaldoMedioCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSaldoMedio)
                        .addGap(20, 20, 20)
                        .addComponent(txtSaldoMedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSaldoMedioCC)
                        .addGap(20, 20, 20)
                        .addComponent(txtSaldoMedioCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblMenorSaldo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMenorSaldoTitular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMenorSaldoTipo)
                        .addGap(18, 18, 18)
                        .addComponent(txtMenorSaldoValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblMaiorSaldo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMaiorSaldoTitular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMaiorSaldoTipo)
                        .addGap(18, 18, 18)
                        .addComponent(txtMaiorSaldoValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lblBancoNome;
    private javax.swing.JLabel lblMaiorSaldo;
    private javax.swing.JLabel lblMaiorSaldoTipo;
    private javax.swing.JLabel lblMaiorSaldoTitular;
    private javax.swing.JLabel lblMenorSaldo;
    private javax.swing.JLabel lblMenorSaldoTipo;
    private javax.swing.JLabel lblMenorSaldoTitular;
    private javax.swing.JLabel lblSaldoMedio;
    private javax.swing.JLabel lblSaldoMedioCC;
    private javax.swing.JLabel lblSaldoMedioCP;
    private javax.swing.JFormattedTextField txtMaiorSaldoValor;
    private javax.swing.JFormattedTextField txtMenorSaldoValor;
    private javax.swing.JFormattedTextField txtSaldoMedio;
    private javax.swing.JFormattedTextField txtSaldoMedioCC;
    private javax.swing.JFormattedTextField txtSaldoMedioCP;
    // End of variables declaration//GEN-END:variables
}
