/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package utfpr.gui;

import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JRootPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import utfpr.banco.ContaBancaria;
import utfpr.banco.ContaCorrente;

/**
 *
 * @author Free
 */
public class ListaContas extends javax.swing.JInternalFrame {

    ArrayList<ContaBancaria> contas;

    /**
     * Creates new form ListaContas
     */
    public ListaContas(ArrayList dados) {
        initComponents();
        remove_title_bar();
        this.contas = dados;
        carregarDados();
    }

    private void carregarDados() {
        /*Transforma a listagem de clientes em um objeto que 
          possa ser reconhecido e apresentado na tabela*/

        TableModel tm = toTableModel(contas);
        tblContas.setModel(tm);
        configurarTabela();
    }

    private TableModel toTableModel(ArrayList<ContaBancaria> contasBancarias) {

        DefaultTableModel model = new DefaultTableModel(
                new String[]{"Código", "Tipo", "Titular", "Saldo"}, 0)//cabeçalhos da tabela
        {
            Class[] types = new Class[]{String.class, String.class, String.class, Double.class}; //define o formato de apresentação das colunas
            boolean[] canEdit = new boolean[]{false, false, false, false}; //define que não pode editar os valores

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };

        String contaTipo;

        for (ContaBancaria conta : contas) {
            if (conta instanceof ContaCorrente) {
                contaTipo = "Conta corrente";
            } else {
                contaTipo = "Conta poupança";
            }
            model.addRow(new Object[]{conta.getNumero(), contaTipo, conta.getTitular().getNome(), conta.getSaldo()});

        }
        return model;
    }

    private void configurarTabela() {
        //Ajusta o alinhamento do texto do cabeçalho para a esquerda
        DefaultTableCellRenderer renderer = (DefaultTableCellRenderer) tblContas.getTableHeader().getDefaultRenderer();
        renderer.setHorizontalAlignment(JLabel.LEFT);

        //Ajusta o tamanho das colunas para ficar mais bonito
        if (tblContas.getColumnModel().getColumnCount() > 0) {
            tblContas.getColumnModel().getColumn(0).setMinWidth(50);
            tblContas.getColumnModel().getColumn(0).setMaxWidth(100);
            tblContas.getColumnModel().getColumn(1).setMinWidth(100);
            tblContas.getColumnModel().getColumn(2).setMinWidth(100);
        }

    }

    private void remove_title_bar() {
        putClientProperty("ListaContas.isPalette", Boolean.TRUE);
        getRootPane().setWindowDecorationStyle(JRootPane.NONE);
        ((BasicInternalFrameUI) this.getUI()).setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBancoNome = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblContas = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);

        lblBancoNome.setBackground(java.awt.SystemColor.inactiveCaption);
        lblBancoNome.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lblBancoNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBancoNome.setText("Contas");
        lblBancoNome.setAutoscrolls(true);
        lblBancoNome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblBancoNome.setMaximumSize(new java.awt.Dimension(136, 42));
        lblBancoNome.setMinimumSize(new java.awt.Dimension(136, 42));
        lblBancoNome.setOpaque(true);
        lblBancoNome.setPreferredSize(new java.awt.Dimension(136, 42));

        tblContas.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tblContas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Código", "Tipo", "Títular", "Saldo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblContas.setAutoscrolls(false);
        tblContas.setGridColor(java.awt.SystemColor.controlLtHighlight);
        tblContas.setOpaque(false);
        tblContas.setRowHeight(20);
        tblContas.getTableHeader().setReorderingAllowed(false);
        tblContas.setUpdateSelectionOnSort(false);
        jScrollPane1.setViewportView(tblContas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBancoNome, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblBancoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBancoNome;
    private javax.swing.JTable tblContas;
    // End of variables declaration//GEN-END:variables
}
